package com.jyhrie.priestess;

import com.jyhrie.priestess.block.ModBlocks;
import com.jyhrie.priestess.item.ModCreativeTabs;
import com.jyhrie.priestess.item.ModItems;
import net.minecraftforge.eventbus.api.IEventBus;
import net.minecraftforge.fml.common.Mod;
import net.minecraftforge.fml.javafmlmod.FMLJavaModLoadingContext;

@Mod(Priestess.MOD_ID)
public class Priestess {

    public static final String MOD_ID = "priestess";

    public Priestess() {
        IEventBus modEventBus = FMLJavaModLoadingContext.get().getModEventBus();

        // Worldgen (dimension, biomes, structures) is not registered here — it ships
        // as datapack JSON generated by `gradlew runData`. See README.md.
        ModItems.register(modEventBus);
        ModBlocks.register(modEventBus);
        ModCreativeTabs.register(modEventBus);
    }

}
