package com.jyhrie.priestess;

import com.jyhrie.priestess.config.BossStats;
import com.jyhrie.priestess.config.MinibossStats;
import com.jyhrie.priestess.config.MobStats;
import com.jyhrie.priestess.config.WeaponStats;
import com.jyhrie.priestess.block.ModBlocks;
import com.jyhrie.priestess.block.entity.ModBlockEntities;
import com.jyhrie.priestess.effect.ModEffects;
import com.jyhrie.priestess.entity.ModEntities;
import com.jyhrie.priestess.item.ModCreativeTabs;
import com.jyhrie.priestess.item.ModItems;
import com.jyhrie.priestess.oripathy.OripathyEvents;
import com.jyhrie.priestess.progression.DungeonSync;
import com.jyhrie.priestess.weapons.ModWeapons;
import com.jyhrie.priestess.weapons.network.WeaponNetwork;
import com.jyhrie.priestess.world.dimension.AnchorReport;
import com.jyhrie.priestess.world.dimension.ModStructurePlacements;
import com.jyhrie.priestess.world.terra.TerraElevationFunction;
import com.jyhrie.priestess.world.terra.TerraMapBiomeSource;
import com.jyhrie.priestess.world.terra.TerraReliefFunction;
import com.mojang.serialization.Codec;
import net.minecraft.core.registries.Registries;
import net.minecraft.world.level.biome.BiomeSource;
import net.minecraft.world.level.levelgen.DensityFunction;
import net.minecraftforge.common.MinecraftForge;
import net.minecraftforge.eventbus.api.IEventBus;
import net.minecraftforge.fml.ModLoadingContext;
import net.minecraftforge.fml.common.Mod;
import net.minecraftforge.fml.config.ModConfig;
import net.minecraftforge.fml.javafmlmod.FMLJavaModLoadingContext;
import net.minecraftforge.registries.DeferredRegister;

@Mod(Priestess.MOD_ID)
public class Priestess {

    public static final String MOD_ID = "priestess";

    // Worldgen is datapack JSON generated by `gradlew runData`. These two are the exception: a
    // codec has to exist in the registry *before* that JSON can be read back.
    private static final DeferredRegister<Codec<? extends BiomeSource>> BIOME_SOURCES =
            DeferredRegister.create(Registries.BIOME_SOURCE, MOD_ID);

    private static final DeferredRegister<Codec<? extends DensityFunction>> DENSITY_FUNCTIONS =
            DeferredRegister.create(Registries.DENSITY_FUNCTION_TYPE, MOD_ID);

    static {
        BIOME_SOURCES.register("terra_map", () -> TerraMapBiomeSource.CODEC);
        // The registry stores a plain Codec while DensityFunction.codec() hands back a
        // KeyDispatchDataCodec, so unwrap it, as vanilla's DensityFunctions.register does.
        DENSITY_FUNCTIONS.register("terra_elevation",
                () -> TerraElevationFunction.CODEC.codec());
        DENSITY_FUNCTIONS.register("terra_relief",
                () -> TerraReliefFunction.CODEC.codec());
    }

    public Priestess() {
        IEventBus modEventBus = FMLJavaModLoadingContext.get().getModEventBus();

        ModItems.register(modEventBus);
        ModBlocks.register(modEventBus);
        ModBlockEntities.register(modEventBus);
        ModCreativeTabs.register(modEventBus);
        ModEffects.register(modEventBus);
        ModEntities.register(modEventBus);

        // These two lines and one in ModCreativeTabs are every reference to weapons/ from
        // outside the folder, which is what keeps it removable.
        ModWeapons.register(modEventBus);
        WeaponNetwork.register();

        BIOME_SOURCES.register(modEventBus);
        DENSITY_FUNCTIONS.register(modEventBus);
        // Same reason as the two above: the structure-set JSON names a placement type, and
        // the codec for it has to be in the registry before that JSON can be parsed.
        ModStructurePlacements.register(modEventBus);

        // Oripathy: the capability type is a mod-bus registration, everything that acts on
        // it (attaching it to players, symptoms, the /oripathy command) is a Forge-bus one.
        modEventBus.addListener(OripathyEvents::registerCapabilities);
        MinecraftForge.EVENT_BUS.register(OripathyEvents.class);

        // Reports where this world put its one-per-world dungeons, to operators on login.
        MinecraftForge.EVENT_BUS.register(AnchorReport.class);

        // SERVER, so it lives in the world save: it gates what a world permits and therefore
        // has to travel with it. The progression handlers are @Mod.EventBusSubscriber and
        // register themselves, but both read this config, so it has to exist first.
        ModLoadingContext.get().registerConfig(ModConfig.Type.SERVER, PriestessConfig.SPEC);

        // Balance is COMMON rather than SERVER: it belongs to the installation, so one edit
        // retunes every save. Split by tier — see the note on Stats.
        ModLoadingContext.get().registerConfig(ModConfig.Type.COMMON, BossStats.SPEC,
                "priestess/boss.toml");
        ModLoadingContext.get().registerConfig(ModConfig.Type.COMMON, MinibossStats.SPEC,
                "priestess/miniboss.toml");
        ModLoadingContext.get().registerConfig(ModConfig.Type.COMMON, MobStats.SPEC,
                "priestess/mob.toml");
        ModLoadingContext.get().registerConfig(ModConfig.Type.COMMON, WeaponStats.SPEC,
                "priestess/weapon.toml");

        // The lockdown's client half. Without this the client predicts a break the server is
        // going to refuse, and a sealed block shatters and comes back rather than not moving.
        DungeonSync.register();
    }

}
